---
title: "Diamond_Dataset_Single_Variable"
author: "Rakesh"
date: "August 8, 2015"
output: html_document
---
```{r}

# Create a histogram of the price of
# all the diamonds in the diamond data set.

# TYPE YOUR CODE BELOW THE LINE
# =======================================
qplot(price, data = diamonds, geom = "histogram", col = 'blues')

#if you want to draw a line of the centre of the histogram which is basically your median then you can do something like this one :
#my distribution is long tailed so you need to do somehting about it 
```

```{r}
a <- subset(diamonds, diamonds$price < 500)
b <- subset(diamonds, diamonds$price < 250)
c <- subset(diamonds, diamonds$price >= 15000)
```

```{r}
# Explore the largest peak in the
# price histogram you created earlier.

# Try limiting the x-axis, altering the bin width,
# and setting different breaks on the x-axis.

# There won’t be a solution video for this
# question so go to the discussions to
# share your thoughts and discover
# what other people find.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Submit your final code when you are ready.

# TYPE YOUR CODE BELOW THE LINE
# ======================================================================
ggplot(aes(x= price), data = diamonds) + 
  geom_histogram() + 
  scale_x_continuous(limits = c(826, 830))

#by dividing the scale of my x-axis, we are able to see which will be the peak values 

```

```{r}
ggplot(aes(x= price), data = diamonds) + 
  geom_histogram() + 
  scale_x_continuous(cut(diamonds$price, breaks = c(0, 1000, 2000, 3000)))
#Everything_abour_histogram <http://blog.datacamp.com/make-histogram-ggplot2/>
```










