---
title: "Diamond_Dataset_Single_Variable"
author: "Rakesh"
date: "August 8, 2015"
output: html_document
---
```{r}

# Create a histogram of the price of
# all the diamonds in the diamond data set.

# TYPE YOUR CODE BELOW THE LINE
# =======================================
qplot(price, data = diamonds, geom = "histogram", col = 'blues')

#if you want to draw a line of the centre of the histogram which is basically your median then you can do something like this one :
#my distribution is long tailed so you need to do somehting about it 
```

```{r}
a <- subset(diamonds, diamonds$price < 500)
b <- subset(diamonds, diamonds$price < 250)
c <- subset(diamonds, diamonds$price >= 15000)
```

```{r}
# Explore the largest peak in the
# price histogram you created earlier.

# Try limiting the x-axis, altering the bin width,
# and setting different breaks on the x-axis.

# There won’t be a solution video for this
# question so go to the discussions to
# share your thoughts and discover
# what other people find.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Submit your final code when you are ready.

# TYPE YOUR CODE BELOW THE LINE
# ======================================================================
ggplot(aes(x= price), data = diamonds) + 
  geom_histogram() + 
  scale_x_continuous(limits = c(826, 830))

#by dividing the scale of my x-axis, we are able to see which will be the peak values 

```

```{r}
ggplot(data=diamonds, aes(diamonds$price)) + 
  geom_histogram(breaks=seq(0, 1000, by = 50), 
                 col="red", 
                 fill="green", 
                 alpha = .2) 
#Everything_abour_histogram <http://blog.datacamp.com/make-histogram-ggplot2/>
```

```{r}
# Break out the histogram of diamond prices by cut.

# You should have five histograms in separate
# panels on your resulting plot.

# TYPE YOUR CODE BELOW THE LINE
# ======================================================

ggplot(data=diamonds, aes(diamonds$price)) + 
  geom_histogram(breaks=seq(0, 5000, by = 200), 
                 col="red", 
                 fill="green", 
                 alpha = .2) +
  facet_wrap(~cut)

#if you want to divide your histogram based on a particular pattern then you should use the facet_wrap

```

```{r}
# In the two last exercises, we looked at
# the distribution for diamonds by cut.

# Run the code below in R Studio to generate
# the histogram as a reminder.

# ===============================================================

qplot(x = price, data = diamonds) + facet_wrap(~cut, scales = "free_y")
                                                                               
# ===============================================================

# In the last exercise, we looked at the summary statistics
# for diamond price by cut. If we look at the output table, the
# the median and quartiles are reasonably close to each other.

# diamonds$cut: Fair
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     337    2050    3282    4359    5206   18570 
# ------------------------------------------------------------------------ 
# diamonds$cut: Good
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     327    1145    3050    3929    5028   18790 
# ------------------------------------------------------------------------ 
# diamonds$cut: Very Good
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     336     912    2648    3982    5373   18820 
# ------------------------------------------------------------------------ 
# diamonds$cut: Premium
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     326    1046    3185    4584    6296   18820 
# ------------------------------------------------------------------------ 
# diamonds$cut: Ideal
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     326     878    1810    3458    4678   18810 

# This means the distributions should be somewhat similar,
# but the histograms we created don't show that.

# The 'Fair' and 'Good' diamonds appear to have 
# different distributions compared to the better
# cut diamonds. They seem somewhat uniform
# on the left with long tails on the right.

# Let's look in to this more.

# Look up the documentation for facet_wrap in R Studio.
# Then, scroll back up and add a parameter to facet_wrap so that
# the y-axis in the histograms is not fixed. You want the y-axis to
# be different for each histogram.

# If you want a hint, check out the Instructor Notes.


```

```{r}
# Create a histogram of price per carat
# and facet it by cut. You can make adjustments
# to the code from the previous exercise to get
# started.

# Adjust the bin width and transform the scale
# of the x-axis using log10.

# Submit your final code when you are ready.

# ENTER YOUR CODE BELOW THIS LINE.
# ===========================================================================
qplot(x = price/carat, data = diamonds) + facet_wrap(~cut, scales = "free_y")
# Answer from book 
# #qplot(x =price/carat, data = diamonds, color = I('black'), fill = I('#099DD9'), binwidth = 600) +
#   facet_wrap(~cut, scales="free_y")
```


```{r}
# Investigate the price of diamonds using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color.

# There won’t be a solution video for this
# exercise so go to the discussion thread for either
# BOXPLOTS BY CLARITY, BOXPLOT BY COLOR, or BOXPLOTS BY CUT
# to share you thoughts and to
# see what other people found.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# =================================================================
```


```{r}
# Investigate the price of diamonds using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color.

# There won’t be a solution video for this
# exercise so go to the discussion thread for either
# BOXPLOTS BY CLARITY, BOXPLOT BY COLOR, or BOXPLOTS BY CUT
# to share you thoughts and to
# see what other people found.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# =================================================================
qplot(y= price, x= cut, data = diamonds, geom = 'boxplot') 
# qplot(x = color, y = price, data = diamonds, geom = "boxplot") + 
#   coord_cartesian(ylim = c(0,8000))

# For boxplots, we use y parameter for the continuous data and the x parameter for the categorical data.

```

```{r}
You can use the function IQR() to find the interquartile range. Pass it a subset of the diamonds data frame.

For example...
IQR(subset(diamonds, price <1000)$price)
Remember subset returns a data frame so we need to use $price on the end to access that variable.









```























